#include "system.h"

/* SystemCoreClock = 8000000; */
#ifndef __Vendor_SysTickConfig
#define __Vendor_SysTickConfig
#endif
#define TIM1_PRESCALER 0x0001

void SystemInit(void) 
{
  // Clocks configuration
  RCC->CR |= (RCC_CR_HSION);
  RCC->APB2ENR = (RCC_APB2ENR_SYSCFGEN | RCC_APB2ENR_TIM16EN );
  RCC->APB1ENR = (RCC_APB1ENR_DAC1EN | RCC_APB1ENR_TIM6EN); 
  RCC->AHBENR = (RCC_AHBENR_GPIOFEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOAEN | RCC_AHBENR_ADC12EN);


  // TIM16, interrupt 125ms
  TIM16->DIER = TIM_DIER_UIE; // 0x40; // TIM_DIER_TIE;
  TIM16->PSC = 0x000F;
  TIM16->ARR = 31250;
  TIM16->CR1 = (TIM_CR1_CEN);




  // TIM6 for DAC clock
  TIM6->PSC = 0x0000;
  TIM6->ARR = 0x00000040;
  TIM6->CR2 = (TIM_CR2_MMS_1);
  TIM6->CR1 = (TIM_CR1_CEN | TIM_CR1_ARPE);
  
  // -- NUCLEO board specific
  // NUCLEO onboard led
  GPIOB->MODER = (GPIO_MODER_MODER3_0);
  // swdio A13, swdclk A14
  GPIOA->MODER |= (GPIO_MODER_MODER13_1 | GPIO_MODER_MODER14_1);
  GPIOA->PUPDR |= (GPIO_PUPDR_PUPDR13_0 | GPIO_PUPDR_PUPDR14_1);
  GPIOA->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR13_1 | GPIO_OSPEEDER_OSPEEDR13_0);
  // vcp_rx A15, vcp_tx A2
  GPIOA->MODER |= (GPIO_MODER_MODER2_1 | GPIO_MODER_MODER15_1);
  GPIOA->PUPDR |= (GPIO_PUPDR_PUPDR2_0 | GPIO_PUPDR_PUPDR15_0);
  

  // -- External interrupts configuration
  // interrupt inputs
  GPIOA->MODER |= (GPIO_MODER_MODER3_0 | GPIO_MODER_MODER7_0); // interrupts on buttons
  GPIOA->PUPDR |= (GPIO_PUPDR_PUPDR3_1 | GPIO_PUPDR_PUPDR7_1);
  // exti control registers 
  SYSCFG->EXTICR[0] = SYSCFG_EXTICR1_EXTI3_PA;
  SYSCFG->EXTICR[1] = SYSCFG_EXTICR2_EXTI7_PA;
  // exti rising edge
  EXTI->IMR = 0x1F800088;   // EXTI_RTSR_RT3+EXTI_RTSR_RT7+default
  EXTI->RTSR = 0x00000088;  // EXTI_RTSR_RT3+EXTI_RTSR_RT7


  /* -- DMA */
  DMA1_Channel1->CNDTR = 0x26;
  DMA1_Channel1->CCR = (DMA_CCR_TCIE | DMA_CCR_HTIE | DMA_CCR_TEIE | DMA_CCR_CIRC | DMA_CCR_MINC | DMA_CCR_PSIZE_1 | DMA_CCR_MSIZE_1);
  DMA1_Channel1->CPAR = 0x50000040;
  DMA1_Channel1->CMAR = 0x20000514; // RANDOMLY CHOSEN MEMORY !!!!!!!!!!!!!!!!!!!!
  DMA1_Channel3->CPAR = 0x40007408;
  DMA1_Channel3->CMAR = 0x20000514;
  DMA1_Channel3->CCR = (DMA_CCR_TCIE | DMA_CCR_HTIE | DMA_CCR_TEIE | DMA_CCR_CIRC| DMA_CCR_DIR | DMA_CCR_MINC | DMA_CCR_PSIZE_1 | DMA_CCR_MSIZE_1);
  for(int i=1000; i>0; i--);
  DMA1_Channel1->CCR |= (DMA_CCR_EN);
  DMA1_Channel3->CCR |= (DMA_CCR_EN);
  /* ADC DAC */
  GPIOA->MODER |= (GPIO_MODER_MODER0_1 | GPIO_MODER_MODER0_0 | GPIO_MODER_MODER4_0 | GPIO_MODER_MODER4_1);
  ADC1->CR = (ADC_CR_ADVREGEN_0);
  ADC1->CFGR = (ADC_CFGR_DMACFG | ADC_CFGR_EXTSEL_0 | ADC_CFGR_EXTSEL_2 | ADC_CFGR_EXTSEL_3 | ADC_CFGR_EXTEN_0 | ADC_CFGR_OVRMOD);
  ADC1->SQR1 = (ADC_SQR1_SQ1);
  ADC1_2_COMMON->CCR = (ADC12_CCR_CKMODE_0);
  ADC1->CR |= (ADC_CR_ADEN);
  DAC1->CR = (DAC_CR_DMAUDRIE1 | DAC_CR_DMAEN1 | DAC_CR_TEN1);
  for(int i=1000; i>0; i--);
  DAC1->CR |= DAC_CR_TEN1;

  /* remap dac->dma */
  SYSCFG->CFGR1 |= SYSCFG_CFGR1_TIM6DAC1Ch1_DMA_RMP;
  




}
